# .github/workflows/generate-gallery.yml
name: Generate Image Gallery JSON and HTML

on:     # Trigger on any changes inside the pics folder
  workflow_dispatch:     # Allow manual trigger as well

jobs:
  generate-gallery:
    runs-on: ubuntu-latest

    env:
      FOLDER_NAME: 'Onam-25'  # Set your folder name here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Gather image files list
      id: list_files
      run: |
        echo "Listing files in pics/$FOLDER_NAME"
        files=$(ls pics/$FOLDER_NAME | grep -E '\.(jpg|jpeg|png|gif)$' | sort | jq -R -s -c 'split("\n")[:-1]')
        echo "files=$files" >> $GITHUB_OUTPUT

    - name: Create JSON file with image names
      run: |
        echo '${{ steps.list_files.outputs.files }}' > $FOLDER_NAME.json
        mv $FOLDER_NAME.json .

    - name: Generate HTML file
      run: |
        cat > index.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Image Gallery</title>
  <style>
    /* Full CSS here, same as before */
  </style>
</head>
<body>
  <h1>Image Gallery</h1>
  <div class="gallery" id="gallery"></div>

  <div class="popup-overlay" id="popup">
    <div class="popup-content">
      <button class="close-btn" id="closeBtn" aria-label="Close popup">&times;</button>
      <img id="popupImg" src="#" alt="Full sized image" />
      <a id="downloadBtn" class="download-btn" download="" title="Download Image" aria-label="Download image">
        &#8681;
      </a>
    </div>
  </div>

  <script>
    const gallery = document.getElementById('gallery');
    const popup = document.getElementById('popup');
    const popupImg = document.getElementById('popupImg');
    const downloadBtn = document.getElementById('downloadBtn');
    const closeBtn = document.getElementById('closeBtn');

    const folderName = "${FOLDER_NAME}";

    fetch(folderName + ".json")
      .then(res => res.json())
      .then(images => {
        gallery.innerHTML = images.map(img =>
          `<img src="pics/${folderName}/${img}" alt="" data-src="pics/${folderName}/${img}">`).join('');
      });

    function openPopup(src) {
      popup.classList.add('active');
      popupImg.src = src;
      downloadBtn.href = src;
      downloadBtn.setAttribute('download', src.split('/').pop());
      document.body.style.overflow = 'hidden';
    }

    function closePopup() {
      popup.classList.remove('active');
      popupImg.src = '#';
      document.body.style.overflow = '';
    }

    closeBtn.addEventListener('click', closePopup);
    popup.addEventListener('click', e => {
      if (e.target === popup) closePopup();
    });

    window.addEventListener('keydown', e => {
      if (e.key === 'Escape' && popup.classList.contains('active')) {
        closePopup();
      }
    });

    gallery.addEventListener('click', e => {
      if (e.target.tagName === 'IMG') {
        openPopup(e.target.getAttribute('data-src'));
      }
    });
  </script>
</body>
</html>
EOF

    - name: Commit and push generated files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html $FOLDER_NAME.json
        git commit -m "Auto-updated gallery HTML and JSON for $FOLDER_NAME"
        git push
      continue-on-error: true
